"""Prometheus metrics exposed by the Celery worker via a background HTTP server."""
import threading
from prometheus_client import Histogram, Counter, start_http_server
import os

METRICS_PORT = int(os.getenv("WORKER_METRICS_PORT", "9091"))

BATCH_TASK_DURATION = Histogram(
    "worker_batch_task_duration_seconds",
    "Time taken to complete a batch inference task",
    buckets=[1, 5, 10, 30, 60, 120, 300],
)

BATCH_TOKENS_GENERATED = Counter(
    "worker_tokens_generated_total",
    "Total tokens generated by the batch worker",
)


def start_metrics_server() -> None:
    """Start Prometheus metrics HTTP server in a daemon thread."""
    def _serve():
        start_http_server(METRICS_PORT)

    t = threading.Thread(target=_serve, daemon=True)
    t.start()
